version: '3'
services:
  backend:
    container_name: hpp_backend
    image: hpp_backend:1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - hpp_app
  frontend:
    container_name: hpp_frontend
    image: hpp_frontend:1.0.0
    build:
      context: UI
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - hpp_app
networks:
  hpp_app:
    driver: bridge